language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t ishan84/react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true ishan84/react-app npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-app"
 env: "DockerApp-env"
 bucket_name: "elasticbeanstalk-us-east-1-486125389802"
 bucket_path: "docker-app"
 on:
  branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
